### PR TITLE
wisdom-monitor : add params to routes service

### PR DESCRIPTION
**Pull request by jetien**
share source, type and default value.
useful to share simple API for front dev.

### CODE REVIEW

**Comment by cescoffier** [comment]
@barjo can you have a look - it may be something close to the RAML stuff

**Comment by cescoffier** [comment]
@barjo is traveling at the moment (forgot that). He should be back on business tomorrow or Friday.

**Comment by barjo** [comment]
Just arrive in the airport, I will work on it tomorow (^^)b-- Jo on the goOn Apr 21, 2015 16:13, Julien ETIEN <notifications@github.com> wrote: share source, type and default value.
useful to share simple API for front dev.



You can view, comment on, or merge this pull request online at:
  https://github.com/wisdom-framework/wisdom/pull/476

Commit Summary

  wisdom-monitor : add params to routes service, and share source, type and default value


File Changes

  
    M
    extensions/wisdom-monitor/src/main/java/org/wisdom/monitor/extensions/wisdom/RouteModel.java
    (18)
  
  
    M
    extensions/wisdom-monitor/src/main/resources/templates/monitor/routes.thl.html
    (11)
  


Patch Links:

  https://github.com/wisdom-framework/wisdom/pull/476.patch
  https://github.com/wisdom-framework/wisdom/pull/476.diff

**Comment by barjo** [comment]
@jetien Not sure if you got the chance to have a look at it, but there is the https://github.com/wisdom-framework/wisdom/tree/master/extensions/wisdom-raml monitor extensions that provides information in the form of a Raml API for each Controller. 

It works by parsing the Controller java source file, and use the raml api-console to display those informations. It supports the watch mode too. 

I am not sure if the feature in this PR overlapp with it. I am temped to say no? 

WDYT?

**Comment by jetien** [comment]
Hi @barjo, really thanks by sharing this extension. I just start to use it
on my project but it seems completely that respond to my PR.
However, when I try to show it on monitor there is an infinite loading and
the XController.raml is not displayed

2015-04-23 12:49 GMT+02:00 Jonathan Bardin <notifications@github.com>:

> @jetien <https://github.com/jetien> Not sure if you got the chance to
> have a look at it, but there is the
> https://github.com/wisdom-framework/wisdom/tree/master/extensions/wisdom-raml
> monitor extensions that provides information in the form of a Raml API for
> each Controller.
>
> It works by parsing the Controller java source file, and use the raml
> api-console to display those informations. It supports the watch mode too.
>
> I am not sure if the feature in this PR overlapp with it. I am temped to
> say no?
>
> WDYT?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wisdom-framework/wisdom/pull/476#issuecomment-95537324>
> .
>



-- 

Julien ETIEN | Ingénieur Etudes et Développement
1 rue Fleming - Bureau 11 - 17000 La Rochelle
*+33 (0)5 16 49 04 84 | +33 (0)6 07 88 76 72*
website : www.ubidreams.com
Skype : julien.etien

**Comment by barjo** [comment]
@jetien The javascript api-console from Raml is very strick. Could you open an issue about that, it's possible that some of the raml generated by the plugin does not zork properly with their js api-console.

**Comment by cescoffier** [comment]
So what do we do with this PR ?

**Comment by barjo** [comment]
@cescoffier I think it's too close to the wisdom-souce-model that is within the wisdom-raml extension for now.

**Comment by cescoffier** [comment]
Ok, closing the PR then.

**Pull request closed without merging**
